# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('SQLCoreProject/resources', 'resources'),
        ('language', 'language'),
    ],
    hiddenimports=[
        'language.lang',
        'language.ko',
        'language.en',
        'SQLCoreProject.data.SQLgate',
        'SQLCoreProject.data.SQLteach',
        'SQLCoreProject.data.SQLvault',
        'SQLCoreProject.data.SQLqueryinput',
        'SQLCoreProject.data.SQLresultToWide',
        'SQLCoreProject.plugin.memory_onboarding',
        'SQLCoreProject.plugin.PluginController',
        'SQLCoreProject.plugin.company_data_loader',
        'SQLCoreProject.plugin.duckdb_plugin',
        'SQLCoreProject.plugin.sqlite_plugin',
        'SQLCoreProject.plugin.controller',
        'SQLCoreProject.plugin.company_log_plugin',
        'SQLCoreProject.ui.SQLtoolbar',
        'SQLCoreProject.ui.SQLgateUI',
        'SQLCoreProject.ui.SQLtabsheet',
        'SQLCoreProject.ui.SQLmultibridge',
        'SQLCoreProject.ui.SQLtable_left',
        'SQLCoreProject.ui.SQLmulti_result',
        'SQLCoreProject.ui.SQLhint',
        'SQLCoreProject.ui.SQLhotkey',
        'SQLCoreProject.ui.runner',
        'SQLCoreProject.core.SQLquery_analysis',
        'SQLCoreProject.core.SQLFlowVisualizer',
        'SQLCoreProject.core.SQLInterpreterCore',
        'SQLCoreProject.core.CTEconditions',
        'SQLCoreProject.core.AST_each_CTE',
        'SQLCoreProject.core.ASTaggregation',
        'SQLCoreProject.core.ASTKeywordsAnalyzer',
        'SQLCoreProject.core.ASTwithAnalyzer',
        'SQLCoreProject.core.ASTtcAnalyzer',
        'SQLCoreProject.core.CTEselect',
        'SQLCoreProject.core.CTEjoin',
        'SQLCoreProject.core.CTEkeywords',
        'SQLCoreProject.core.ASTselectAnalyzer',
        'SQLCoreProject.core.ASTjoinAnalyzer',
        'SQLCoreProject.utils.sql_constants',
        'SQLCoreProject.utils.walker_core',
        'SQLCoreProject.utils.path_utils',
        'sqlglot',
        'duckdb',
        'pandas',
        'openpyxl',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='OrrerySQL',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    icon='SQLCoreProject/resources/ONS.ico',
    onefile=True
)
