SQL_KEYWORDS = [
    "SELECT", "FROM", "WHERE", "AND", "OR", "NOT", "INSERT", "INTO", "VALUES", "UPDATE",
    "SET", "DELETE", "CREATE", "TABLE", "PRIMARY", "KEY", "FOREIGN", "REFERENCES", "TRUE", "FALSE",
    "DROP", "ALTER", "ADD", "COLUMN", "ORDER", "BY", "GROUP", "HAVING", "AS", "ON", "COPY",
    "JOIN", "INNER", "LEFT", "RIGHT", "OUTER", "LIMIT", "OFFSET", "DISTINCT", "UNION", "EXIST",
    "ALL", "EXISTS", "IN", "IS", "NULL", "BETWEEN", "LIKE", "ASC", "DESC", "THEN", "END",
    "AUTO_DETECT", "DELIM", "QUOTE", "ESCAPE", "HEADER", "SAMPLE_SIZE", "ALL_VARCHAR",
    "NORMALIZE_NAMES", "PRAGMA", "DESCRIBE", "EXPLAIN", "SHOW", "IMPORT", "EXPORT", "WITH"
]

SQL_FUNCTIONS = [
    "COUNT", "SUM", "AVG", "MIN", "MAX", "GROUP_CONCAT", "MEDIAN", "MODE", "STDDEV_SAMP", "STDDEV_POP",
    "VAR_POP", "VAR_SAMP", "UPPER", "LOWER", "TRIM", "LTRIM", "RTRIM", "REPLACE", "SUBSTR", "CONCAT",
    "LENGTH", "REVERSE", "LEFT", "RIGHT", "SPLIT_PART", "REGEXP_MATCHES", "REGEXP_REPLACE",
    "NOW", "CURRENT_DATE", "CURRENT_TIMESTAMP", "EXTRACT", "DATE_TRUNC", "DATE_PART", "DATE_DIFF",
    "DATE_ADD", "DATE_SUB", "YEAR", "MONTH", "DAY", "HOUR", "MINUTE", "SECOND", "ABS", "ROUND",
    "CEIL", "FLOOR", "POWER", "SQRT", "EXP", "LN", "LOG", "RANDOM", "COALESCE", "IFNULL", "NULLIF",
    "CASE", "WHEN", "INTEGER", "CAST", "TRY_CAST", "GREATEST", "LEAST", "READ_CSV", "READ_CSV_AUTO",
    "READ_JSON", "READ_PARQUET", "GLOB", "LIST_AGG", "UNNEST", "STRUCT_PACK", "STRUCT_EXTRACT",
    "STRPTIME", "STRFTIME", "EPOCH_MS", "TO_TIMESTAMP"
]
